spring.application.name=vip_system
# 配置端口号
server.port=9999
# 数据源的配置
spring.datasource.username=your_username
# 这里是你电脑上装的数据库的密码
spring.datasource.password=your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/vip_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
# mybatis-plus 配置
#配置实体类别名
mybatis-plus.type-aliases-package=org.westos.entity
#配置mapper接口对应的xml文件放置的位置
mybatis-plus.mapper-locations=classpath:org/westos/mapper/*.xml
#配置日志输出级别，输出sql语句
logging.level.org.westos.mapper=debug
